<a href="https://colab.research.google.com/github/lakshmiprabhakar/DATA_SCIENCE_LAB/blob/main/cyc2_prgm7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from numpy import array, diag, zeros
from scipy.linalg import pinv
from numpy.linalg import svd

A = array([[1, 2], [3, 4], [5, 6]])
print("A=",A)
print("Pseudoinverse of matrix A calculated by function pinv is:")
print(pinv(A))

U, s, VT = svd(A)
d = 1.0 / s
D = zeros(A.shape)
D[:A.shape[1], :A.shape[1]] = diag(d)
B = VT.T.dot(D.T).dot(U.T)

print("Pseudoinverse of matrix A calculated by using svd is:")
print(B)


A= [[1 2]
 [3 4]
 [5 6]]
Pseudoinverse of matrix A calculated by function pinv is:
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
Pseudoinverse of matrix A calculated by using svd is:
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
