<a href="https://colab.research.google.com/github/lakshmiprabhakar/DATA_SCIENCE_LAB/blob/main/cyc2_prgm4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("Example for broadcasting: ")
v=np.array([1,2,3])
w=np.array([4,5])
print("v = ",v)
print("w=",w)
print("Outer product of above vectors: ")
print(np.reshape(v,(3,1))*w)
x=np.array([[1,2,3],[4,5,6]])
print("x = ",x)
print("Resultant matrix after adding the vector x to each row of matrix v: ")
print(x+v)
print("Example for broadcasting fails: ")
print("Adding the vector x to each column of matrix w will generate an error")
print("Solution: Reshape the matrix w then the result will be: ")
print(x+np.reshape(w,(2,1)))

Example for broadcasting: 
v =  [1 2 3]
w= [4 5]
Outer product of above vectors: 
[[ 4  5]
 [ 8 10]
 [12 15]]
x =  [[1 2 3]
 [4 5 6]]
Resultant matrix after adding the vector x to each row of matrix v: 
[[2 4 6]
 [5 7 9]]
Example for broadcasting fails: 
Adding the vector x to each column of matrix w will generate an error
Solution: Reshape the matrix w then the result will be: 
[[ 5  6  7]
 [ 9 10 11]]
